name: Run nginx image
on:
    push:
        branches:
          - main
      
jobs:
    login_docker:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
         username: ${{secrets.DOCKER_HUB_USERNAME}}
         password: ${{secrets.DOCKER_HUB_ACSSESS_TOKEN}}

      - name: Run nginx image
        uses: docker pull nginx:latest

      - name: Run NGINX 
        uses: |
          docker run -d --name mynginx -p 8000:80 nginx:latest
    
